"""initial migration

Revision ID: b8b099e2b009
Revises: 
Create Date: 2024-11-01 10:03:08.340124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b099e2b009'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('completed', 'pending', 'none', name='status_type'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_table', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
